#!/usr/bin/perl
# apt-cache-search-color
use strict;

my $re = shift;

open(my $acs, '-|', "apt-cache search $re") or die($!);
my @pkg = <$acs>;
my $i=0;
my $j=0;
my @c = (197,106,212,100,32,220,196,112);

my $termBold = "\033[1m";
my $termReset = "\033[0m";

for(@pkg) {
  $j++; # 1

  my($package,$desc) = m/(.+?)\s+-\s+(.+)/g;
  printf("$termBold%03d$termBold\033[38;5;$c[$i]m%25s$termReset \033[38;5;155m$desc$termReset\n",$j,$package);

  if($i == scalar(@c)-1) {
    $i = 0;
  } else {
    $i++;
  }
}

