#!/usr/bin/perl
# apt-cache-search-color
use strict;

my $re = shift;

open(my $acs, '-|', "apt-cache search $re") or die($!);
my @pkg = <$acs>;
my $i=0;
my $j=0;
my @c = (197,106,212,100,32,220,196,112);
for(@pkg) {
  $j++; # 1
  if($i == scalar(@c)-1) {
    $i = 0;
  }

  my($package,$desc) = m/(.+)\s+-\s+(.+)/g;
  printf("\033[1m%03d\033[1m\033[38;5;$c[$i]m%25s\033[0m \033[38;5;155m$desc\033[0m\n",$j,$package);
  $i++;
}

